
import React from 'react';

export const TRANSLATIONS = {
  bn: {
    appName: 'আমার খামার',
    tagline: 'সরাসরি কৃষকের থেকে নিরাপদ পণ্য',
    heroTitle: 'সরাসরি যাচাইকৃত কৃষকদের কাছ থেকে কিনুন',
    heroSub: 'নিরাপদ, সহজ এবং ন্যায্য কৃষি বাজার',
    joinFarmer: 'কৃষক হিসেবে যোগ দিন',
    buyProducts: 'পণ্য কিনুন',
    verifiedFarmers: 'যাচাইকৃত কৃষক',
    securePayments: 'নিরাপদ পেমেন্ট',
    directFromFarms: 'সরাসরি খামার থেকে',
    featuredProducts: 'জনপ্রিয় পণ্য',
    whyUs: 'কেন আমাদের প্ল্যাটফর্ম?',
    fairPrice: 'কৃষকদের জন্য ন্যায্য মূল্য',
    noMiddlemen: 'কোন মধ্যস্বত্বভোগী নেই',
    safeTrans: 'নিরাপদ লেনদেন',
    category: 'বিভাগ',
    location: 'অবস্থান',
    price: 'মূল্য',
    quantity: 'পরিমাণ',
    orderNow: 'অর্ডার করুন',
    addProducts: 'নতুন পণ্য যোগ করুন',
    farmerDashboard: 'কৃষক ড্যাশবোর্ড',
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    name: 'নাম',
    phone: 'মোবাইল নম্বর',
    village: 'গ্রাম',
    union: 'ইউনিয়ন',
    district: 'জেলা',
    farmingCategory: 'চাষের ধরণ',
    register: 'নিবন্ধন করুন',
    vegetables: 'শাকসবজি',
    fish: 'মাছ',
    rice: 'চাল',
    fruits: 'ফল',
    livestock: 'গবাদি পশু'
  },
  en: {
    appName: 'Amar Khamar',
    tagline: 'Safe products direct from farmers',
    heroTitle: 'Buy directly from verified farmers',
    heroSub: 'Safe, simple, and fair agricultural marketplace',
    joinFarmer: 'Join as a Farmer',
    buyProducts: 'Buy Products',
    verifiedFarmers: 'Verified Farmers',
    securePayments: 'Secure Payments',
    directFromFarms: 'Direct from Farms',
    featuredProducts: 'Featured Products',
    whyUs: 'Why Our Platform?',
    fairPrice: 'Fair price for farmers',
    noMiddlemen: 'No middlemen',
    safeTrans: 'Safe transactions',
    category: 'Category',
    location: 'Location',
    price: 'Price',
    quantity: 'Quantity',
    orderNow: 'Order Now',
    addProducts: 'Add New Product',
    farmerDashboard: 'Farmer Dashboard',
    adminDashboard: 'Admin Dashboard',
    name: 'Name',
    phone: 'Mobile Number',
    village: 'Village',
    union: 'Union',
    district: 'District',
    farmingCategory: 'Farming Category',
    register: 'Register',
    vegetables: 'Vegetables',
    fish: 'Fish',
    rice: 'Rice',
    fruits: 'Fruits',
    livestock: 'Livestock'
  }
};

export const CATEGORIES = [
  { id: 'vegetables', bn: 'শাকসবজি', en: 'Vegetables', icon: '🥬' },
  { id: 'fish', bn: 'মাছ', en: 'Fish', icon: '🐟' },
  { id: 'rice', bn: 'চাল', en: 'Rice', icon: '🌾' },
  { id: 'fruits', bn: 'ফল', en: 'Fruits', icon: '🍎' },
  { id: 'livestock', bn: 'গবাদি পশু', en: 'Livestock', icon: '🐄' },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name_bn: 'তাজা লাল শাক',
    name_en: 'Fresh Red Spinach',
    price: 30,
    unit: 'মুঠি',
    category: 'vegetables' as const,
    image: 'https://picsum.photos/seed/spinach/400/300',
    farmerName: 'রহিম মিয়া',
    location: 'সাভার, ঢাকা',
    isVerified: true,
  },
  {
    id: '2',
    name_bn: 'দেশি রুই মাছ',
    name_en: 'Local Rui Fish',
    price: 350,
    unit: 'কেজি',
    category: 'fish' as const,
    image: 'https://picsum.photos/seed/fish/400/300',
    farmerName: 'আব্দুল করিম',
    location: 'চলন বিল, নাটোর',
    isVerified: true,
  },
  {
    id: '3',
    name_bn: 'নাজিরশাইল চাল',
    name_en: 'Nazirshail Rice',
    price: 75,
    unit: 'কেজি',
    category: 'rice' as const,
    image: 'https://picsum.photos/seed/rice/400/300',
    farmerName: 'সোলেমান আলী',
    location: 'দিনাজপুর',
    isVerified: false,
  },
  {
    id: '4',
    name_bn: 'মিষ্টি আম',
    name_en: 'Sweet Mango',
    price: 120,
    unit: 'কেজি',
    category: 'fruits' as const,
    image: 'https://picsum.photos/seed/mango/400/300',
    farmerName: 'জসিম উদ্দিন',
    location: 'রাজশাহী',
    isVerified: true,
  },
];
